### ISSUE TITLE
sepolicy: Add vendor prefix to qcom_ims_prop

### ISSUE THREAD

**Issue by ghost** [CBG-leeco/android_device_leeco_msm8996-common#1]
Hi!
Fluid doesn't build without [it](https://review.lineageos.org/c/LineageOS/android_device_oneplus_oneplus3/+/308725/).
And it's not only in radio.te file, replace it everywhere.

**Comment by CBG-leeco** [comment]
i wil on next days..or you can make a pr..

**Comment by CBG-leeco** [comment]
Solved..
